### PR TITLE
Add custom option for the HtmlElement type

### PR DESCRIPTION
**Pull request by Freymaurer**
- Added suggested changes from issue #104 .
- Added unit tests based of existing tests and style
- run tests :white_check_mark:

### CODE REVIEW

**Comment by baronfel** [comment]
This seems good to me 👍. @Krzysztof-Cieslak what's it take to do a release in this repo? Tag push?

**Comment by Freymaurer** [comment]
Would really love to see a release as soon as possible 👍

**Comment by Krzysztof-Cieslak** [comment]
@baronfel, yeah: https://github.com/ionide/Fornax/blob/master/.github/workflows/release.yml#L3-L6

**Comment by Freymaurer** [comment]
Sorry for the spam, just really need at least an timeframe @baronfel .

**Comment by baronfel** [comment]
sorry, just push 0.14.1, which includes this change.

**Comment by Freymaurer** [comment]
@baronfel sry it's me again. As far as i understand it, there is no nuget package for v0.14.0, so i cannot actually use the new version 😢

**Comment by Freymaurer** [comment]
Vielen Dank!

**Comment by Freymaurer** [comment]
Hey and me again 😅 I use dotnet local tools and updated my `dotnet-tools.json` to the new version. Used `dotnet tool restore` (this time no error, so package was found), but the function, i need, is still not accessible. I checked the version `dotnet fornax version` which returned `0.13.1` for me. Not sure if the Fornax.Core.dll gets updated via dotnet tools, so i created a new fornax project somewhere else (`fornax new`) and it worked there. I copied the dll's to my prev. project and it works now, thanks!

Just wanted to tell you about it, as i don't know if the "updating" of fornax is expected to work or not. 

And one more thing, when you intilialize a new fornax project, there is currently an error, introduced in my PR.

In `layout.fsx`

````fsharp
body [] [
          nav [Class "navbar"] [
            div [Class "container"] [
              div [Class "navbar-brand"] [
                a [Class "navbar-item"; Href "/"] [
                  img [Src "/images/bulma.png"; Alt "Logo"]
                ]
                // Custom is not recognized as HtmlProperties, but as my freshly introduced type.
                span [Class "navbar-burger burger"; HtmlProperties.Custom ("data-target", "navbarMenu")] [
                  span [] []
                  span [] []
                  span [] []
                ]
              ]
              div [Id "navbarMenu"; Class "navbar-menu"] menuEntries
            ]
          ]
          yield! bodyCnt
          custom "" [] []
        ]
````

No matter what, thanks for all your effort, highly appreciate it.

**Pull request merged**
