### PR TITLE
Update to .NET 5

### PR DESCRIPTION
**Pull request by laenas**
I think this pushes it forward (and closes out #77)- though I want to call a little attention to the targetting of `Fornax.Core` - which I have left at `netstandard2.0` - as pushing it to `net5.0` has implications for things like `FSIRefs` and its (current - 2) version compatibility handling.

That said, if we want to burn our ships on the shore of .NET 5, it's an easy enough update to the PR! 😉

### CODE REVIEW

**Comment by laenas** [comment]
Prior to opening the PR, I was waffling a bit on that `netstandard` / `net5.0` switch - and having run stuff locally under `net5.0`.  Having sorted out the cause of that initial failed build, I figured I'd take a peek, and it sure does seem like without Core being targeted to net5.0, we don't get support for stuff like `#r "nuget: Package"` support.

Is there a way around this that I'm not immediately seeing? :)

**Comment by baronfel** [comment]
It's fine to bump to net5.0, that's required for latest FCS anyway.

**Comment by laenas** [comment]
@baronfel 
> Update CHANGELOG to insert a new (fake) version line
> dotnet fake build -T Pack
> Move the `.nupkg` from `/out/` to my local nuget cache location
> dotnet tool install -g Fornax --version (my fake version)
> tweak the sample site in `/samples/` to use an `#r "nuget: "` reference and a `$"{}"` interpolation to add NET5 / F# 5 specific features.
> `fornax watch`
> Site generates as expected

**Comment by baronfel** [comment]
Thanks!

**Pull request merged**
