### PR TITLE
Add support for paging

### PR DESCRIPTION
**Pull request by robertpi**
Will generate multiple summary pages when number of posts pass a certain amount

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Maybe we could define page size in the `globalloader.fsx` rather than using constant value?

**Comment by robertpi** [comment]
Yeah, I can make that change if you like. I didn't do that as a user will probably need to customize index.fsx in someway when setting up their site.

**Comment by robertpi** [comment]
Done.

**Comment by Krzysztof-Cieslak** [comment]
Awesome, thanks.

**Pull request merged**
