### PR TITLE
New varible for SiteContents to determine build type

### PR DESCRIPTION
**Pull request by robertpi**
This gives a cleaner way to test whether the refresh js socket should be injected or not

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Hey, 

I’ve been thinking about something like that for a while and I think I’d prefer to use `#WATCH` define  when it watch-mode rather than passing bool around.

**Comment by robertpi** [comment]
I think this would be easier to implement:
```
#if WATCH
#endif
```
Does that look okay?

**Comment by Krzysztof-Cieslak** [comment]
Oh, that's exactly what I've meant.  I shouldn't write messages on GitHub before first tea ;-)

**Comment by Krzysztof-Cieslak** [comment]
I've implemented this in b8fffa974d43a99744a65e75a1ff44a89bbc83e4

**Pull request closed without merging**
