### PR TITLE
Improve perf by caching generators

### PR DESCRIPTION
**Pull request by robertpi**
Small change, order of magintude improvement. Tested on 185 page blog:

Pre-change - Generation time: 00:04:59.3250690
Post-change - Generation time: 00:00:19.2490206

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Shouldn’t it also invalidate cache when the generator file is changed?

**Comment by robertpi** [comment]
Oh yeah, I was only thinking about the build mode where it runs and exits. I'll take another look at the the watch mode.

**Comment by robertpi** [comment]
Support cache invalidation in watch mode now.

**Comment by Krzysztof-Cieslak** [comment]
We probably could go even further than this and invalidate cache only in some particular cases (invalidate all when config or any loader has changed, invalidate single entry when the generator has changed. ). But even this is great, thanks a lot!

**Comment by robertpi** [comment]
I thought about that, and agree it would be a better solution I didn't do it for two reasons:
- This bug and knowing where the route directory is makes a little tricky to be sure what the cache key related to the file would be: https://github.com/ionide/Fornax/issues/63
- I don't think it would impact perf that much as all the files are regenerated anyway

Next logical step for better perf, for watch mode at least, is calculating which files have changed and just regenerating them.

**Pull request merged**
