### PR TITLE
better release script (and overall updates)

### PR DESCRIPTION
**Pull request by baronfel**
This updates:
* FAKE to .net 6 alphas
* Paket to latest
* adds versioning from the changelog
* updates FCS
* slims down the fake build script massively, relying on Directory.Build.props and the changelog to drive metadata
* adds a release github action that uses a nuget key (which I'll generate)

### CODE REVIEW

**Comment by baronfel** [comment]
Fixes #101

**Comment by baronfel** [comment]
final blocker before merge is that the Fornax package doesn't have @ionide as an owner. @Krzysztof-Cieslak can you change that so I can provision a key and merge?

**Review by cartermp — APPROVED** [review]

**Comment by baronfel** [comment]
don't merge quite yet - doing a side-by-side diff with the generated packages in nuget.info shows a layout difference from 0.13.1

**Comment by baronfel** [comment]
content issue fixed - the template needs to be _inside_ the packed tools dir, which is why the linkbase stuff was there before.  this is now ready to gone once fornax package ownership is moved to the ionide org.

**Comment by baronfel** [comment]
fornax is moved to the ionide org, key is set in this repo's settings, now to merge, tag and verify the pipeline.

**Pull request merged**
